# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Delete list of destinations from destination list"


class Input:
    DESTINATIONLISTID = "destinationListId"
    ORGANIZATIONID = "organizationId"
    PAYLOAD = "payload"


class Output:
    pass


class DDeleteInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "destinationListId": {
      "type": "integer",
      "title": "Destination List ID",
      "description": "Unique ID for destination list",
      "order": 2
    },
    "organizationId": {
      "type": "integer",
      "title": "Organization ID",
      "description": "Organisation ID",
      "order": 1
    },
    "payload": {
      "type": "array",
      "title": "Payload",
      "description": "List of destinations",
      "items": {
        "$ref": "#/definitions/destinationsIdsList"
      },
      "order": 3
    }
  },
  "required": [
    "destinationListId",
    "organizationId",
    "payload"
  ],
  "definitions": {
    "destinationsIdsList": {
      "type": "integer",
      "title": "destinationsIdsList",
      "properties": {
        "id": {
          "type": "integer",
          "title": "Destinations Ids List",
          "description": "example, 1234",
          "order": 1
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DDeleteOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
