# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    DESTINATION_LIST_ID = "destination_list_id"
    API_KEY = "api_key"
    API_SECRET = "api_secret"
    ORGANIZATION_ID = "organization_id"
    

class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api_key": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Key",
      "description": "Cisco Umbrella API key",
      "order": 1
    },
    "api_secret": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Secret Key",
      "description": "Cisco Umbrella API secret key",
      "order": 2
    },
    "organization_id": {
      "type": "integer",
      "title": "Organization ID",
      "description": "ID of your Cisco Umbrella organization",
      "order": 3
    },
    "destination_list_id": {
      "type": "integer",
      "title": "Destination List ID",
      "description": "ID for the destination list",
      "order": 4
    }   
  },
  "required": [
    "api_key",
    "api_secret",
    "organization_id"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "displayType": "password",
          "description": "The shared secret key",
          "format": "password"
        }
      },
      "required": [
        "secretKey"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
